### ISSUE TITLE
Charts Menu selection fails to generate chart

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Topsoil#122]
After pasting data into table, clicking Charts / error ellipse chart or scatterplot menu item does nothing because in initializeAndShow method of TopsoilManWindow.java dataTableToSet has length 0.  This causes the method to return with no action.  Apparently dataTableToSet is not initialized after data pasting.

**Comment by clementparizot** [comment]
Working on it.

**Comment by johnzeringue** [comment]
@clementparizot, was this the bug affecting you?

**Comment by johnzeringue** [comment]
Also, thanks for claiming this. It's helpful to me to know what you're planning on addressing so that I can mark it as assigned to you.
