### ISSUE TITLE
String.format breaks when html contains %20 in path to resource

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Topsoil#130]
In JavaScriptChart.java, the generation of HTML_TEMPLATE uses URLs made from the full local path.  If these paths have spaces in them, they write as "%20".  String.format throws an error when this is encountered.  I renamed my directories without spaces and all worked well.  Suggestion - maybe we should use relative paths, since inside Topsoil's directories we control naming.   Note this is related to issue #122 but not the full story there.

**Comment by johnzeringue** [comment]
I'm not sure that we can use relative paths, since these files live inside the JAR. I'll look into it, though.

**Comment by johnzeringue** [comment]
Wasn't actually fixed in #131. This still needs to be addressed.
