### ISSUE TITLE
Import data file should create new data table tab

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Topsoil#141]
Currently, with no tabs, import creates a tab, but when a tab exists and has focus, import overwrites the tab.  The behavior should be consistent and import should always create a new tab.  A user may well be surprised to lose their data with the current behavior.  This improvement also anticipates having a chart open and tied to a data table and then opening a second chart for another data table in order to compare, etc. 

It may be that further discussion is warranted about the menus and the buttons.  For example, a menu titled "Data Table" could contain "Import from file", "Paste from clipboard", "Open", "Save", "Save As", etc. (in some logical order) and remove the need for buttons at all.  Each of the first three actions listed would create a new tab.

**Comment by johnzeringue** [comment]
I agree. Currently, you can't edit empty tables in any meaningful way, but particularly when that's added, this is a much better behavior.
