### ISSUE TITLE
Introduce dependency injection

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/Topsoil#176]
Introducing dependency injection (DI) would make the codebase more readable and testable. It's important to note that this would only be done on the `org.cirdles.topsoil.app` half of the project (the standalone application).

My preference would be Google's [Guice](https://github.com/google/guice). This doesn't have to happen all at once, but I'll probably start poking it in this weekend by adding in a shared `Application` object that carries Topsoil's name, version, etc. and would manage the different directory paths. I'd like to get rid of the constants that carry these.

**Comment by bowring** [comment]
I'm sold ... after you break the ground, I will see about retrofitting
ET_Redux, at least moving forward.

On Wed, Jun 3, 2015 at 7:45 PM, John Zeringue <notifications@github.com>
wrote:

> Introducing dependency injection (DI) would make the codebase more
> readable and testable. It's important to note that this would only be done
> on the org.cirdles.topsoil.app half of the project (the standalone
> application).
>
> My preference would be Google's Guice <https://github.com/google/guice>.
> This doesn't have to happen all at once, but I'll probably start poking it
> in this weekend by adding in a shared Application object that carries
> Topsoil's name, version, etc. and would manage the different directory
> paths. I'd like to get rid of the constants that carry these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/issues/176>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.
