### ISSUE TITLE
Add Tera-Wasserburg concordia

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/Topsoil#226]
In the latest versions of Topsoil (the v1 alphas), it is no longer possible to create a Tera-Wasserburg concordia, because that functionality has yet to be reimplemented.

**Comment by DemianNelson** [comment]
Any idea when Tera-Wasserburg concordia plots will be available?

**Comment by johnzeringue** [comment]
Sorry this has been taking so long. We'll try and get this finished in the next couple weeks.

@noahmclean, I recall you wanted the Wetherill and Tera-Wasserburg concordias being options for the same plot. Am I remembering correctly?

If so, can you explain how this is done for 207/235-206/238 data? It's not clear to me how the conversion to 238/206-207/206 is even possible given that we don't know the masses.

**Comment by DemianNelson** [comment]
Someone please correct me if I'm wrong but we assume that 238U/235U is constant and equal to 137.818. If you know the 238U/206Pb and 207Pb/235U you can determine the the 207Pb/206Pb.

238/206 * 207/235 = x (some number)

then use x to get 207/206

x = 238/235 * 207/206       (**238/235 = 137.818**)

207/206 = x  / 137.818

Hopefully that helps? Looking forward to plotting TW, thanks for your help!

**Comment by johnzeringue** [comment]
@DemianNelson, that's exactly what I was thinking of.
