### ISSUE TITLE
Paste from clipboard not working

### ISSUE THREAD

**Issue by jthevos** [CIRDLES/Topsoil#228]
Using OSX 10.9.5 and Java version 1.8.0_60, paste from clipboard functionality does not respond when clicked. I have confirmed that the data was in the clipboard by pasting into both a text editor and Excel.

**Comment by johnzeringue** [comment]
@jthevos, thanks again for reporting. If you have time, steps/data to reproduce are really the only way I can debug this.

**Comment by johnzeringue** [comment]
Closed because @jthevos never provided steps to reproduce.
