### ISSUE TITLE
Add feedback

### ISSUE THREAD

**Issue by donnerlt** [CIRDLES/Topsoil#229]
When there are issues pasting or getting data into the application, there is no feedback whatsoever. There should be an error message or some information that shows something went wrong. Right now, it just does nothing.

**Comment by johnzeringue** [comment]
@donnerlt, thanks again, but I'd appreciate it if you'd be more specific. There are all sorts of "issues" that can occur when copying and pasting data, and it's hard to address this issue without you first specifying which of those are insufficiently handled.

If you have a clear vision for what this needs to be, by all means, create a pull request, but if you don't add some detail here in the next few days, I'm going to go ahead and close this.

**Comment by donnerlt** [comment]
Any feedback at all would be good, though if it could give you some kind of message that says what the issue is, that'd be good as well. 
It could be something as simple as an error message popping up saying "There was an error with your data. Please see the wiki for more info" with a link to the wiki, OR it could be more detailed depending on how importing data works that tells you the exact issue and how to fix it. Obviously the latter would be better, but that might be going a bit above and beyond. At the very least, it should have a message after clicking the button in the middle if no information is being read. 

I hope this helps a bit more!

**Comment by johnzeringue** [comment]
@donnerlt, thanks for the followup. I still don't think we're on the same page, though.

There are two sources of error in the copy-paste feature: the parser and its input. The parser interprets its input as a tab-separated values (TSV) file. Without going into too much detail, most strings, including this comment, are valid TSV. This makes three main categories of errors: parser bugs, invalid TSV (very rare), and non-sensical data (like this comment). Any of the three might be a good target for an issue. However, it's inappropriate to address them all at once as they each carry unique challenges.

I'm *assuming* that what happened in your case was that the entire contents of the sample data went into a single header. This isn't necessarily incorrect behavior (for example, IE table copy-paste doesn't produce TSV, although it can be treated as such). I'm interested to discover what is actually your issue, though. Can you provide steps to reproduce and a screenshot from afterwards?
