### ISSUE TITLE
Not intuitive, needed help finding and importing data

### ISSUE THREAD

**Issue by traviszc** [CIRDLES/Topsoil#233]
1) Navigating github is confusing. (There are not good signifiers to tell me where to go or how to download the latest version)
2) I dont feel like i should have to go read a whole wiki just to figure out where to get data and how to import it   (maybe have sample data already loaded in and told how to use it)
3) Once in the ellipse chart, the zooming in and out features are very confusing and i quickly lost myself in the chart and could no longer see the data, or the ellipse chart. ( Finally found the Reset View button)

**Comment by johnzeringue** [comment]
@traviszc, thanks for contributing. However, this issue is neither specific nor constructive. Issues should be either single bugs or enhancements with clear requirements for closure.

If you would still like some of your ideas in the issue tracker, please make them actionable.
