### ISSUE TITLE
Datasets (data tables) are not handled robustly.

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Topsoil#284]
There are several issue with the way datasets (data tables) are handled.

First is the  interchangeable use of dataset and data table - I think we should settle on one or the other.

User can save datasets with the same name and Topsoil does not inform the user of the collision.  Then, the same name appears twice, etc. in the list of files available to the user for loading and they can each be loaded.  Each dataset can be loaded more than once, which is confusing and non-standard behavior as well.  The saved instances are different, as editing a cell in one does not change the others with the same name.  

Also, when "Save Data  Table" is invoked, Topsoil does not differentiate between "save" and "save-as".  I suggest that Topsoil use the standard save / save as metaphor with relation to file paths.

When a cell is changed, the saved dataset keeps the change, but when a row is de-selected, the saved dataset does not keep the change - these changes should be persistent.

**Comment by johnzeringue** [comment]
I've replaced this issue #287, #288, #289, #290, and #291.

In the future, please try and report multiple problems in separate issues.

**Comment by bowring** [comment]
It is a matter of judgement - to me they are all part of the same issue - a
redesign of the file handling interface -;)

On Mon, Feb 29, 2016 at 2:49 PM, John Zeringue <notifications@github.com>
wrote:

> I've replaced this issue #287
> <https://github.com/CIRDLES/Topsoil/issues/287>, #288
> <https://github.com/CIRDLES/Topsoil/issues/288>, #289
> <https://github.com/CIRDLES/Topsoil/issues/289>, #290
> <https://github.com/CIRDLES/Topsoil/issues/290>, and #291
> <https://github.com/CIRDLES/Topsoil/issues/291>.
>
> In the future, please try and report multiple problems in separate issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/issues/284#issuecomment-190353561>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
GitHub: https://github.com/bowring

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by johnzeringue** [comment]
> It's tempting sometimes to see multiple issues, convince yourself that they are related, and then file a single bug on the whole thing.
Don't do that. You may very well be right that the issues are related -- but you may also be wrong, and in either case, two different issues deserve two different bug reports... Each bug must be fixed and tested in its own context, and that won't work if they're all stuffed in the same bug report.

**Comment by bowring** [comment]
The problem is that bugs are hierarchical and a mere linear approach to
each bug in turn will miss the bigger point that the file handling system
needs replacement - this is a flaw in the design that produces these
lower-level bugs. So maybe the label should be enhancement, but I
definitely want to discourage piece-meal repairs associated with a laundry
list of bugs and rather want to inspire a rethinking of the interface.

On Mon, Feb 29, 2016 at 3:07 PM, John Zeringue <notifications@github.com>
wrote:

> It's tempting sometimes to see multiple issues, convince yourself that
> they are related, and then file a single bug on the whole thing.
> Don't do that. You may very well be right that the issues are related --
> but you may also be wrong, and in either case, two different issues deserve
> two different bug reports... Each bug must be fixed and tested in its own
> context, and that won't work if they're all stuffed in the same bug report.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/Topsoil/issues/284#issuecomment-190360649>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles
GitHub: https://github.com/bowring

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.
