### ISSUE TITLE
Automatically detect whether input data has headers

### ISSUE THREAD

**Issue by marottajb** [CIRDLES/Topsoil#324]
i.e. If supplied with: 

207Pb*/235U	±2σ (%)	206Pb*/238U	±2σ (%)	corr coef
29.165688743	1.519417676	0.712165893	1.395116767	0.918191745
29.031535970	1.799945600	0.714916493	1.647075269	0.915069472

Topsoil should be able to determine (or guess) that the top row is a header row, and apply it to the TableColumn names.

**Comment by alaubus** [comment]
New enhancement to do: it should be possible to manage the import of files and contents with multiple lines of headers (zero, one or two), and skip the invalid lines of values (instead of displaying NaN in the table).
