### ISSUE TITLE
Data table is difficult to read

### ISSUE THREAD

**Issue by marottajb** [CIRDLES/Topsoil#366]
The table can be difficult to read. Some possible steps for making it more readable:
- Make font bold
- Change font
- Increase font size
- Change TableView/TableCell background color

**Comment by noahmclean** [comment]
Is it possible to change the font color to a darker shade of gray, or just black?

**Comment by marottajb** [comment]
The font color of the text in the table cells is already black. It might not appear fully black because of the font style combined with the size.

**Comment by marottajb** [comment]
Table font changed and bolded in #376.
