### ISSUE TITLE
Dynamically assign variables to data columns

### ISSUE THREAD

**Issue by marottajb** [CIRDLES/Topsoil#367]
As it stands, only five columns are allowed in each Topsoil table, and each of those five columns has a preset plotting variable attached to it. When importing data, the user is forced to select five of their columns and the variables that they are associated with, and Topsoil reorganizes the data for them.

The user should be able to have any number of columns, and those columns shouldn't have to have variables assigned to them right away. The order of the columns should also be independent of the order of the variables.

**Comment by noahmclean** [comment]
And don't forget about calculation columns!  Columns where the result is calculated from entries in other columns.  A great example would be "206Pb/238U date" calculated from "206Pb/238U", where date = 1/lambda238 * log( 206Pb/238U + 1 ).  This seems simple but is incredibly integral to U-Pb geochronology workflows, with parallels in many other isotope systems that don't have the benefit of @bowring working for a decade plus on (U-Pb/ET)_Redux.
