### ISSUE TITLE
Isochron values should be visible at plot boundary

### ISSUE THREAD

**Issue by marottajb** [CIRDLES/Topsoil#372]
See below:
![uthplot_v3](https://user-images.githubusercontent.com/11744455/27150012-9c087138-5113-11e7-8343-c8fab4157984.png)

**Comment by noahmclean** [comment]
You can find the formulas used to determine both the offset between the plot box and the isochron labels and the angle of the text field in my MATLAB code.  

I'm not sure what's going on with those axis labels... Chrome kinda sucks at svg sometimes.
