### ISSUE TITLE
import data uncertainty problem

### ISSUE THREAD

**Issue by adh152** [CIRDLES/Topsoil#380]
As I showed #%*&#%( Noah, when importing data as a 1-sigma %, the uncertainty looks fine in the import window, but when it's displayed in the table, it is unexpectedly (and incorrectly) multiplied by 100.

**Comment by bowring** [comment]
I saw it demo'ed - when the data set is imported and the user sets the sigma choice as 1, this problem occurs, but not when 2 is chosen.
