### ISSUE TITLE
Not seeing regression line on this pull request - using UPb dataset.

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Topsoil#401]
Topsoil Version: v1.0.0-alpha.10-135-g0f4e9a9
Java Version: 1.8.0_144
Operating System: Mac OS X 10.12.6
***

**Comment by emilycoleman** [comment]
This was just so Jake could add the fix he found, should've mentioned in the comments

**Comment by marottajb** [comment]
Fixed by #400
