### ISSUE TITLE
Request: Pre-populated drop down fields

### ISSUE THREAD

**Issue by ryanickert** [CIRDLES/Topsoil#436]
I import data from the clipboard to use Topsoil.  When I see the Data Import Helper, all of the drop down fields are unpopulated by default.  It would be a huge efficiency increase if the default was that they had a reasonable value.  For example, the columns could default to [X, sigmaX, Y, sigmaY, rho] or [X,Y,sigmaX,sigmaY,rho].

For me, it would be really easy to change my clipboard data to fit a default arrangement of columns and save having to do the same fourteen clicks every time I import a data set.

**Comment by marottajb** [comment]
One feature we've talked about is looking at the titles of the columns, and testing how similar they are to some expected value (X, Y...), basically trying to "guess" which of the columns are for which variables.

**Comment by cwmagee** [comment]
Can you set it up so that cirdles opens with the same column headers it closed with? Guessing might work well for some systems, like Sr and Nd, but for others it would not work so well.

**Comment by marottajb** [comment]
We could do that for .topsoil project files, but I think the issue in question is with importing a csv, tsv, or txt file with data in it. @ryanickert

**Comment by ryanickert** [comment]
I've only ever imported from the clipboard.  I copy five columns from excel, and use Topsoil to plot.

**Comment by cwmagee** [comment]
So it it possible to have a user settings file which populates column headings whenever you start Topsoil?

**Comment by marottajb** [comment]
The "Classic" data template will automatically assign the first five column variables as x, y, sigma-x, sigma-y, and rho, in that order.
