### ISSUE TITLE
cannot open a topsoil project

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Topsoil#437]
Hi all,
Nice work on the latest topsoil.  I like the interface with the imported table, where one can select which columns you would like to see in a table to guide the selecting/delecting of plots.  I was curious to see what constitutes a .topsoil project (does it include plots?) so I saved one but Topsoil will not open it.  
[NR first topsoils test v3alpha.zip](https://github.com/CIRDLES/Topsoil/files/3044006/NR.first.topsoils.test.v3alpha.zip)

**Comment by marottajb** [comment]
Thanks for testing it out! I put up another pre-release that should solve the problem you're having.

**Comment by NicoleRayner** [comment]
Hi Jake,

Happy to test it! It’s in my best interest!  I have a few other thoughts but also recognize that this is just a start so don’t want to bombard you with issues for things that you are intending to do anyway. Do you want some nitpicky feedback at this point, or hold my fire…

Nicole

**Comment by marottajb** [comment]
It's the most helpful to have each issue separate, but if you have a list of small things, you can send it to me at marottajb@g.cofc.edu.
