### ISSUE TITLE
What is the purpose of the "Live Update Axes' Min/Max" checkbox under Axis Styling?

### ISSUE THREAD

**Issue by GarreBrenn** [CIRDLES/Topsoil#456]
I notice that when the view is changed and the checkbox is not selected, the X Min/X Max/Y Min/Y Max fields remain stagnant. When the checkbox _is_ selected, those values do change as I alter the view window. I experimented to see if I exported the graph the resulting svg file would have the mins and maxes set to the values in the field, but they were not.

**Comment by marottajb** [comment]
The text fields containing the axes' min/max values react to changes in the view window by default, and the live update checkbox is there to allow a user to turn that feature off if they want to. "Update" refers to updating the values in the text fields, not updating the view window. Changing the values in the text fields won't affect the svg plot unless the user clicks "Set Extents".

**Comment by GarreBrenn** [comment]
What is the practical usage of this feature? I guess I can't see why anyone would want to turn the live update off.

**Comment by GarreBrenn** [comment]
I suppose I just don't understand why anybody wouldn't want the values to be live updating.

**Comment by marottajb** [comment]
The only use case I remember discussing was the event that a user wants to have a specific range that they want to zoom back to without typing it out again. The min/max values wouldn't be overwritten when they manipulate the plot, then they could just click "Set Extents" again to snap back.

A better option for that particular situation might be to implement a feature allowing users to save "views" of the plot that they can zoom to, but the checkbox was significantly less complex at the time.

**Comment by ryanickert** [comment]
It's pretty useful in practice.  It's nice to be able to explore the data, and then snap back to a pre-set range.

**Comment by GarreBrenn** [comment]
Dr. Bowring and myself have discovered the root of this issue to be something separate (although related). I will close this issue and open a new one that's more relevant to the cause of the problem.
