### ISSUE TITLE
Axis Styling - "Set Extents" button action doesn't appear to be working

### ISSUE THREAD

**Issue by GarreBrenn** [CIRDLES/Topsoil#458]
The way I understand it, the "Set Extents" button's are supposed to update the view window to reflect the XMin/XMax and YMin/YMax values in their associated text fields. However, on clicking either of the buttons, nothing occurs. Therefore, there must be some disconnect between the button action and updating the view window. While Dr. Bowring and I have began tracking the source of the issue, we still haven't been able to find it, although we believe it could have something to do with the Topsoil.js file. At this point, I can't be of much help since I don't know JavaScript.

**Comment by marottajb** [comment]
I'll look into this.
