### ISSUE TITLE
Make the data table editable

### ISSUE THREAD

**Issue by pfif** [CIRDLES/Topsoil#76]
Make the table editable, and propagate the changes to the open Charts.
@johnzeringue We'll speak about how I'm am going to do this by before I actually code it.

**Comment by SHRIMP-RG** [comment]
This would be a big improvement - editing the numbers as well as the headers. 

It would also be helpful to add additional columns and/or add multiple data sets. Right now I can't plot sample 1 vs. sample 2 on the same plot. Would it be possible to (eventually) make a concordia (or X-Y) plot with rows 1-5 representing sample 1, and add to that existing plot rows 6-10 representing sample 2?

Visually, and from a user input standpoint, it would be most convenient to choose the color of the ellipse in the pop-up window that asks the user to 'select the column for each variable'. Then, in the customization window  under the ellipse subheading where you can change the colors, you could add boxes that were □ sample 1, □ sample 2, etc. that you could select to change the color of individual samples. Those sample 1 labels should be editable so a key could be auto-populated and added onto the plot. Those are my thoughts.

**Comment by johnzeringue** [comment]
This is all coming (editing everything, adding columns/rows, two sample plots). When we get to that point, we'll certainly take all input regarding the UI into consideration.

We're getting geared up again as the new semester starts, and I'm hoping for a big release within the next couple of months.

Thanks for the feedback!
