### ISSUE TITLE
Refactor GetDocumentsDirectoryOperation

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/Topsoil#83]
`GetDocumentsDirectoryOperation` should be refactored in order to reduce duplicity and improve testability. Comprehensive documentation and tests need to be added as well.

**Comment by kyserpa** [comment]
I've been looking at and trying to refactor this and will this require me to refactor all the related methods in PlatformDependentOperations and GetApplicationDriectoryOperations?

**Comment by johnzeringue** [comment]
No, I want you to do what I did for `GetApplicationDirectoryOperation` (see f91f084) in `GetDocumentsDirectoryOperation`. I committed too much at once, sorry it's difficult to navigate. Use `Ctrl-F`.

**Comment by johnzeringue** [comment]
This was accomplished in #99. Thanks again, @kyserpa.
