### ISSUE TITLE
Creating chart from data table with unacknowledged headers throws exception

### ISSUE THREAD

**Issue by thomasLevans** [CIRDLES/Topsoil#91]
When importing/copying a data set Topsoil displays a dialogue asking the user if the data contains headers.  If the data does contain headers and the user clicks no, when attempting to create a chart an exception is thrown when attempting to create the chart.

**Comment by johnzeringue** [comment]
A better behavior would be to throw a proper exception from `DatasetReader`, catch it from `TopsoilMainWindow`, and show an error dialog, letting the user know that there was an error parsing the file.

**Comment by johnzeringue** [comment]
Actually, there's really no way to do what I was talking about (which is why the user's input is important). This shouldn't throw an error, though. I'll consider this issue closed when someone submits a pull request testing that an exception is no longer thrown.
